version: '3.9'
services:
  web:
    container_name: dotnet-mvc-starter-app # Name your container
    build:
      context: .
      dockerfile: Dockerfile # Path to your Dockerfile
    ports:
      - '5065:80' # Map container port 80 to host port 5065
    environment:
      - ASPNETCORE_URLS=http://+:80
